// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk2e3CKbfCsAKtlDyCDapGeUScJWggHg4',
    appId: '1:270961120755:web:d66c96afecb32e21e6ae86',
    messagingSenderId: '270961120755',
    projectId: 'acha-1e26e',
    authDomain: 'acha-1e26e.firebaseapp.com',
    storageBucket: 'acha-1e26e.firebasestorage.app',
    measurementId: 'G-V1HJLMC1DF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDlKM9W6sZ_k64phRrxen0xr7dE5fwjmI',
    appId: '1:270961120755:android:43525baf8d4f978fe6ae86',
    messagingSenderId: '270961120755',
    projectId: 'acha-1e26e',
    storageBucket: 'acha-1e26e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1UDgBaF1JF1EAEJfXejs_oputzYfoe38',
    appId: '1:270961120755:ios:cc18713e429277b5e6ae86',
    messagingSenderId: '270961120755',
    projectId: 'acha-1e26e',
    storageBucket: 'acha-1e26e.firebasestorage.app',
    iosBundleId: 'com.example.modul7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1UDgBaF1JF1EAEJfXejs_oputzYfoe38',
    appId: '1:270961120755:ios:cc18713e429277b5e6ae86',
    messagingSenderId: '270961120755',
    projectId: 'acha-1e26e',
    storageBucket: 'acha-1e26e.firebasestorage.app',
    iosBundleId: 'com.example.modul7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk2e3CKbfCsAKtlDyCDapGeUScJWggHg4',
    appId: '1:270961120755:web:cbc1f92d3ad6721ae6ae86',
    messagingSenderId: '270961120755',
    projectId: 'acha-1e26e',
    authDomain: 'acha-1e26e.firebaseapp.com',
    storageBucket: 'acha-1e26e.firebasestorage.app',
    measurementId: 'G-6ZBWTENLC5',
  );
}
