// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALZqUXrFvecMExqW9kk7XA4_s5STc90IY',
    appId: '1:36331035997:web:78bc4ac18302b1d72c9cb4',
    messagingSenderId: '36331035997',
    projectId: 'risma-17d28',
    authDomain: 'risma-17d28.firebaseapp.com',
    storageBucket: 'risma-17d28.firebasestorage.app',
    measurementId: 'G-WX59VF6QFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTsLBfEbbW2ywrw8f6cgqUWEzsbEZY9dg',
    appId: '1:36331035997:android:b25bfaabe952088b2c9cb4',
    messagingSenderId: '36331035997',
    projectId: 'risma-17d28',
    storageBucket: 'risma-17d28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2NstHdS8VAiSZIlExr7-dKZz8wb6Xnqw',
    appId: '1:36331035997:ios:a27cb8112a13e0262c9cb4',
    messagingSenderId: '36331035997',
    projectId: 'risma-17d28',
    storageBucket: 'risma-17d28.firebasestorage.app',
    iosBundleId: 'com.example.modul7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2NstHdS8VAiSZIlExr7-dKZz8wb6Xnqw',
    appId: '1:36331035997:ios:a27cb8112a13e0262c9cb4',
    messagingSenderId: '36331035997',
    projectId: 'risma-17d28',
    storageBucket: 'risma-17d28.firebasestorage.app',
    iosBundleId: 'com.example.modul7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALZqUXrFvecMExqW9kk7XA4_s5STc90IY',
    appId: '1:36331035997:web:5c4c1ebe81b71c102c9cb4',
    messagingSenderId: '36331035997',
    projectId: 'risma-17d28',
    authDomain: 'risma-17d28.firebaseapp.com',
    storageBucket: 'risma-17d28.firebasestorage.app',
    measurementId: 'G-95WVP4V6D6',
  );
}
