// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF0FmDoKptgjrX8P20dsanta7iqISWoI0',
    appId: '1:412949602178:web:4a1c0aa54f94400ef2b99b',
    messagingSenderId: '412949602178',
    projectId: 'rawatin-app',
    authDomain: 'rawatin-app.firebaseapp.com',
    storageBucket: 'rawatin-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBoWHTkz965LS5yRemHkcOr-AFfqAancY',
    appId: '1:412949602178:android:7eb549526f71988cf2b99b',
    messagingSenderId: '412949602178',
    projectId: 'rawatin-app',
    storageBucket: 'rawatin-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxyTj9XkA10qV94DydB3rjGel_LzcSi14',
    appId: '1:412949602178:ios:9227a06d2397b8d7f2b99b',
    messagingSenderId: '412949602178',
    projectId: 'rawatin-app',
    storageBucket: 'rawatin-app.firebasestorage.app',
    iosBundleId: 'com.example.rawatinApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxyTj9XkA10qV94DydB3rjGel_LzcSi14',
    appId: '1:412949602178:ios:9227a06d2397b8d7f2b99b',
    messagingSenderId: '412949602178',
    projectId: 'rawatin-app',
    storageBucket: 'rawatin-app.firebasestorage.app',
    iosBundleId: 'com.example.rawatinApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF0FmDoKptgjrX8P20dsanta7iqISWoI0',
    appId: '1:412949602178:web:8288f61b7b78e77df2b99b',
    messagingSenderId: '412949602178',
    projectId: 'rawatin-app',
    authDomain: 'rawatin-app.firebaseapp.com',
    storageBucket: 'rawatin-app.firebasestorage.app',
  );
}
