// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo2oySU42X6fQuk2diBgr1SHSld7eXeZk',
    appId: '1:400168835204:web:54bb20e5ecae3a4fb14ad1',
    messagingSenderId: '400168835204',
    projectId: 'lumubi-f348a',
    authDomain: 'lumubi-f348a.firebaseapp.com',
    storageBucket: 'lumubi-f348a.firebasestorage.app',
    measurementId: 'G-EQYBR8TN9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEiT3YRXlckYtHkRRVG1s6rOKNmASGXgk',
    appId: '1:400168835204:android:086f9a3dc2ef2c0eb14ad1',
    messagingSenderId: '400168835204',
    projectId: 'lumubi-f348a',
    storageBucket: 'lumubi-f348a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtEX_dYfp-yNCiXHzM3LkrYKVDE_3wjG8',
    appId: '1:400168835204:ios:6b2800cf9539fadcb14ad1',
    messagingSenderId: '400168835204',
    projectId: 'lumubi-f348a',
    storageBucket: 'lumubi-f348a.firebasestorage.app',
    iosBundleId: 'com.example.modul7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtEX_dYfp-yNCiXHzM3LkrYKVDE_3wjG8',
    appId: '1:400168835204:ios:6b2800cf9539fadcb14ad1',
    messagingSenderId: '400168835204',
    projectId: 'lumubi-f348a',
    storageBucket: 'lumubi-f348a.firebasestorage.app',
    iosBundleId: 'com.example.modul7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo2oySU42X6fQuk2diBgr1SHSld7eXeZk',
    appId: '1:400168835204:web:e0816bef6ce9f6c2b14ad1',
    messagingSenderId: '400168835204',
    projectId: 'lumubi-f348a',
    authDomain: 'lumubi-f348a.firebaseapp.com',
    storageBucket: 'lumubi-f348a.firebasestorage.app',
    measurementId: 'G-9429TSQ6PN',
  );
}
