// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1gRZ5sFlVV45Cx8ltXseHfMG3z_f9qwQ',
    appId: '1:896328113715:web:86dec1a4015015b2c64d46',
    messagingSenderId: '896328113715',
    projectId: 'willy-1a493',
    authDomain: 'willy-1a493.firebaseapp.com',
    storageBucket: 'willy-1a493.firebasestorage.app',
    measurementId: 'G-4SZ0LDZ2VQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHSG4wgDawcPOal2Nr7p8o3V0YPkvOWyI',
    appId: '1:896328113715:android:b2a4bd5af29e1fdbc64d46',
    messagingSenderId: '896328113715',
    projectId: 'willy-1a493',
    storageBucket: 'willy-1a493.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvnX-4gzEJRzdiIzoz1n9kipqQm-Pa4TQ',
    appId: '1:896328113715:ios:400d758f356c22c0c64d46',
    messagingSenderId: '896328113715',
    projectId: 'willy-1a493',
    storageBucket: 'willy-1a493.firebasestorage.app',
    iosBundleId: 'com.example.modul7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvnX-4gzEJRzdiIzoz1n9kipqQm-Pa4TQ',
    appId: '1:896328113715:ios:400d758f356c22c0c64d46',
    messagingSenderId: '896328113715',
    projectId: 'willy-1a493',
    storageBucket: 'willy-1a493.firebasestorage.app',
    iosBundleId: 'com.example.modul7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1gRZ5sFlVV45Cx8ltXseHfMG3z_f9qwQ',
    appId: '1:896328113715:web:931defe8a2c0f0dfc64d46',
    messagingSenderId: '896328113715',
    projectId: 'willy-1a493',
    authDomain: 'willy-1a493.firebaseapp.com',
    storageBucket: 'willy-1a493.firebasestorage.app',
    measurementId: 'G-BRNM6K71GP',
  );
}
