// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-0lPO-KmztvqgldzasNauh2S0xqZf1Ro',
    appId: '1:892270469989:web:8a40238d28ae9243d0378c',
    messagingSenderId: '892270469989',
    projectId: 'tasknotesabp',
    authDomain: 'tasknotesabp.firebaseapp.com',
    storageBucket: 'tasknotesabp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX0qXVno3UPqcUq4pPKSV7ZnBZ_CoqEhU',
    appId: '1:892270469989:android:472ae298e356b481d0378c',
    messagingSenderId: '892270469989',
    projectId: 'tasknotesabp',
    storageBucket: 'tasknotesabp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgQxy2_Tz8ZeiQpQ9z3pZx_Alr0GruSyc',
    appId: '1:892270469989:ios:3ee677d194a900b0d0378c',
    messagingSenderId: '892270469989',
    projectId: 'tasknotesabp',
    storageBucket: 'tasknotesabp.firebasestorage.app',
    iosBundleId: 'com.example.taskNotesAbp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgQxy2_Tz8ZeiQpQ9z3pZx_Alr0GruSyc',
    appId: '1:892270469989:ios:3ee677d194a900b0d0378c',
    messagingSenderId: '892270469989',
    projectId: 'tasknotesabp',
    storageBucket: 'tasknotesabp.firebasestorage.app',
    iosBundleId: 'com.example.taskNotesAbp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-0lPO-KmztvqgldzasNauh2S0xqZf1Ro',
    appId: '1:892270469989:web:d35145e4b05586d9d0378c',
    messagingSenderId: '892270469989',
    projectId: 'tasknotesabp',
    authDomain: 'tasknotesabp.firebaseapp.com',
    storageBucket: 'tasknotesabp.firebasestorage.app',
  );
}
