// File generated by FlutterFire CLI.
// Ganti dengan konfigurasi Firebase project Anda.
// Jalankan: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Ganti dengan konfigurasi Firebase Anda
  // Jalankan: flutterfire configure

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCDdK1R-LrW4X0P8mJu2nLXSbEJ_3ifd4',
    appId: '1:171812499125:web:7fd9d4c0569017e25fd8fc',
    messagingSenderId: '171812499125',
    projectId: 'praktikum-flutter-d7773',
    authDomain: 'praktikum-flutter-d7773.firebaseapp.com',
    storageBucket: 'praktikum-flutter-d7773.firebasestorage.app',
    measurementId: 'G-76P7QKGT8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLCLiEzVkvU3Nh3tDAgtj2DRZcURU7Q6Y',
    appId: '1:171812499125:android:b26ffaad84829ffc5fd8fc',
    messagingSenderId: '171812499125',
    projectId: 'praktikum-flutter-d7773',
    storageBucket: 'praktikum-flutter-d7773.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWfgXvwVTsv4pCdIiwGxhN9H0rZWS4fxg',
    appId: '1:171812499125:ios:a1c62a50329686e25fd8fc',
    messagingSenderId: '171812499125',
    projectId: 'praktikum-flutter-d7773',
    storageBucket: 'praktikum-flutter-d7773.firebasestorage.app',
    iosBundleId: 'com.example.modul7',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWfgXvwVTsv4pCdIiwGxhN9H0rZWS4fxg',
    appId: '1:171812499125:ios:a1c62a50329686e25fd8fc',
    messagingSenderId: '171812499125',
    projectId: 'praktikum-flutter-d7773',
    storageBucket: 'praktikum-flutter-d7773.firebasestorage.app',
    iosBundleId: 'com.example.modul7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCDdK1R-LrW4X0P8mJu2nLXSbEJ_3ifd4',
    appId: '1:171812499125:web:49ce1ac1d64732825fd8fc',
    messagingSenderId: '171812499125',
    projectId: 'praktikum-flutter-d7773',
    authDomain: 'praktikum-flutter-d7773.firebaseapp.com',
    storageBucket: 'praktikum-flutter-d7773.firebasestorage.app',
    measurementId: 'G-K8VW7EBMR0',
  );
}
