// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKYYr5y_Bi2DEx4lX3RSJp0wu1zv7gAjA',
    appId: '1:439949789019:web:ee0a0db3151f5acd837c7e',
    messagingSenderId: '439949789019',
    projectId: 'pringgo-979ff',
    authDomain: 'pringgo-979ff.firebaseapp.com',
    storageBucket: 'pringgo-979ff.firebasestorage.app',
    measurementId: 'G-03KJ1JGSX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuGvGkhHUbWd9-UGv83YvDUvuwquXsIqE',
    appId: '1:439949789019:android:b178d87a49b2fbb6837c7e',
    messagingSenderId: '439949789019',
    projectId: 'pringgo-979ff',
    storageBucket: 'pringgo-979ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU-I_KBaOu9Z-2YhSQJoGtxUS83SiNHI8',
    appId: '1:439949789019:ios:483dc53fc1d7dd0b837c7e',
    messagingSenderId: '439949789019',
    projectId: 'pringgo-979ff',
    storageBucket: 'pringgo-979ff.firebasestorage.app',
    iosBundleId: 'com.example.modul7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU-I_KBaOu9Z-2YhSQJoGtxUS83SiNHI8',
    appId: '1:439949789019:ios:483dc53fc1d7dd0b837c7e',
    messagingSenderId: '439949789019',
    projectId: 'pringgo-979ff',
    storageBucket: 'pringgo-979ff.firebasestorage.app',
    iosBundleId: 'com.example.modul7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKYYr5y_Bi2DEx4lX3RSJp0wu1zv7gAjA',
    appId: '1:439949789019:web:12e5d89ac4136934837c7e',
    messagingSenderId: '439949789019',
    projectId: 'pringgo-979ff',
    authDomain: 'pringgo-979ff.firebaseapp.com',
    storageBucket: 'pringgo-979ff.firebasestorage.app',
    measurementId: 'G-F5VV3XCW7W',
  );
}
