// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKfkEzDVsjPABCxm6wKso3Bmj_P3gLOAA',
    appId: '1:362779336588:web:e509244e5f0fb0ea48c0a9',
    messagingSenderId: '362779336588',
    projectId: 'pinspiration-app',
    authDomain: 'pinspiration-app.firebaseapp.com',
    storageBucket: 'pinspiration-app.firebasestorage.app',
    measurementId: 'G-LWJY3TT08D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsLx6vtv770fWvgKsWJLWHMqL4xFp749g',
    appId: '1:362779336588:android:deb9a21caac74cc148c0a9',
    messagingSenderId: '362779336588',
    projectId: 'pinspiration-app',
    storageBucket: 'pinspiration-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMxBEKV_rOKoZcQuWcE0odbzyJpk1L914',
    appId: '1:362779336588:ios:18faae4ba9e656fe48c0a9',
    messagingSenderId: '362779336588',
    projectId: 'pinspiration-app',
    storageBucket: 'pinspiration-app.firebasestorage.app',
    iosBundleId: 'com.example.pinspiration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMxBEKV_rOKoZcQuWcE0odbzyJpk1L914',
    appId: '1:362779336588:ios:18faae4ba9e656fe48c0a9',
    messagingSenderId: '362779336588',
    projectId: 'pinspiration-app',
    storageBucket: 'pinspiration-app.firebasestorage.app',
    iosBundleId: 'com.example.pinspiration',
  );
}
